num1 = int(input("sheiyvane pirveli "))
num2 = int(input("sheiyvane meore"))

print(num1 + num2)
print(num1 - num2)
print(num1 * num2)
print(num1 / num2)
print(num1 % num2) 
print(num1 ** num2)
print(num1 < num2)
print(num1 > num2)
print(num1 <= num2) 
print(num1 >= num2) 
print(num1 == num2)
print(num1 != num2)
